<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>za.co.sindi</groupId>
		<artifactId>sindi-langchain4j-examples</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>sindi-langchain4j-chat-openliberty</artifactId>
	<packaging>war</packaging>

	<developers>
		<developer>
			<name>Buhake Sindi</name>
			<timezone>+2</timezone>
			<roles>
				<role>PROJECT LEAD</role>
			</roles>
		</developer>
	</developers>
	
	<properties>
		<!--Strictly for OpenLiberty-->
		<liberty.env.ENGINE_CACHE_DIR>${project.build.directory}/liberty/wlp/usr/shared/resources/lib/</liberty.env.ENGINE_CACHE_DIR>
	</properties>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>za.co.sindi.llm</groupId>
				<artifactId>sindi-langchain4j-features-bom</artifactId>
				<version>0.0.1-SNAPSHOT</version>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- https://mvnrepository.com/artifact/jakarta.platform/jakarta.jakartaee-api -->
		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.eclipse.microprofile</groupId>
			<artifactId>microprofile</artifactId>
			<type>pom</type>
		</dependency>
		
		<dependency>
			<groupId>za.co.sindi</groupId>
			<artifactId>sindi-langchain4j-spi</artifactId>
			<!--
			<scope>provided</scope>
			-->
		</dependency>
		
		<dependency>
			<groupId>za.co.sindi</groupId>
			<artifactId>sindi-langchain4j-portable-extension</artifactId>
			<!-- 
			<scope>provided</scope>
			-->
		</dependency>
		
		<dependency>
			<groupId>za.co.sindi.llm</groupId>
			<artifactId>sindi-langchain4j-feature</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>pom</type>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>za.co.sindi</groupId>
			<artifactId>sindi-langchain4j-hugging-face</artifactId>
		</dependency>
		
		<dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-embeddings-all-minilm-l6-v2</artifactId>
        </dependency>
    
        <!-- https://mvnrepository.com/artifact/ai.djl.huggingface/tokenizers -->
		<dependency>
		    <groupId>ai.djl.huggingface</groupId>
		    <artifactId>tokenizers</artifactId>
		</dependency>
	</dependencies>
	
	<build>
		<finalName>${project.artifactId}</finalName>
		<pluginManagement>
			<plugins>
				<!-- https://mvnrepository.com/artifact/io.openliberty.tools/liberty-maven-plugin -->
				<plugin>
					<groupId>io.openliberty.tools</groupId>
					<artifactId>liberty-maven-plugin</artifactId>
					<version>3.10.3</version>
					<configuration>
						<!--
						<runtimeArtifact>
							<groupId>io.openliberty</groupId>
							<artifactId>openliberty-runtime</artifactId>
							<version>24.0.0.8</version>
							<type>zip</type>
						</runtimeArtifact>
						-->
						<bootstrapProperties>
							<project.name>${project.build.finalName}</project.name>
							<docragdir>${project.basedir}/docs-for-rag</docragdir>
						</bootstrapProperties>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>io.openliberty.tools</groupId>
				<artifactId>liberty-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>